project:
  type: book

book:
  title: "Mermaid alignment"
  chapters:
    - index.qmd

format:
  html:
    theme: cosmo
    fig-align: center
  docx:
    fig-align: center
  # pdf:
  #   documentclass: scrreprt
  #   fig-align: right

editor: source
